/**
 * Jupyter Notebook (.ipynb) generator
 * Builds a valid notebook from solved lab tasks
 */

function makeMarkdownCell(source) {
  return {
    cell_type: 'markdown',
    metadata: {},
    source: Array.isArray(source) ? source : [source],
  };
}

function makeCodeCell(source, outputs = []) {
  return {
    cell_type: 'code',
    execution_count: null,
    metadata: { collapsed: false },
    source: Array.isArray(source) ? source : [source],
    outputs,
  };
}

function makeOutputs(output, error) {
  if (error) {
    return [{
      output_type: 'stream',
      name: 'stderr',
      text: [error],
    }];
  }
  if (output) {
    return [{
      output_type: 'stream',
      name: 'stdout',
      text: [output],
    }];
  }
  return [];
}

/**
 * Generate a .ipynb notebook from solved lab data
 * @param {object} labData - The parsed Gemini response (includes solveMode)
 * @param {Array} executionResults - Array of { output, error } per task
 */
export function generateNotebook(labData, executionResults = []) {
  const cells = [];
  const isPro = labData.solveMode === 'pro';

  // Global Setup Cell
  const setupLines = [
    '# 🛠️ Global Setup & Library Imports (Auto-generated by Lab Solver AI)\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    'import matplotlib.pyplot as plt\n',
    'import seaborn as sns\n',
    '# Standardize plotting style\n',
    'plt.style.use("seaborn-v0_8-muted")\n'
  ];

  if (isPro) {
    setupLines.push('import tensorflow as tf\n');
    setupLines.push('from tensorflow import keras\n');
    setupLines.push('# Confirm GPU availability (relevant for Colab)\n');
    setupLines.push('print(f"TensorFlow Ready! GPU: {\'Detected\' if tf.config.list_physical_devices(\'GPU\') else \'Not Detected\'}")\n');
  } else {
    setupLines.push('from sklearn.neural_network import MLPClassifier\n');
    setupLines.push('print("Browser-Safety Logic Enabled (Scikit-Learn).")\n');
  }

  cells.push(makeCodeCell(setupLines));

  // Title cell
  cells.push(makeMarkdownCell([
    `# ${labData.reportTitle || 'Lab Report'}\n`,
    `**Subject:** ${labData.subject || 'N/A'}  \n`,
    `**Pipeline:** 🚀 Autonomous Notebook Architect  \n`,
    `**Total Tasks:** ${labData.totalTasks || labData.tasks?.length || 0}  \n`,
    `**Generated by:** Lab Solver AI`,
  ]));

  // Divider
  cells.push(makeMarkdownCell(['---']));

  // One section per task
  labData.tasks?.forEach((task, idx) => {
    const result = executionResults[idx] || {};

    // Task header as markdown
    cells.push(makeMarkdownCell([
      `## Task ${task.taskNumber}: ${task.title}\n`,
      `\n`,
      `### 📝 Description\n`,
      `\n`,
      `${task.description}\n`,
      `\n`,
      `### 🔍 Solution\n`,
      `\n`,
      `${task.solution}\n`,
    ]));

    // Code cell (if task has code)
    if (task.hasCode && task.code) {
      const outputs = makeOutputs(
        result.output || task.expectedOutput || '',
        result.error || null,
      );
      cells.push(makeCodeCell(task.code, outputs));
    }

    // Output analysis as markdown
    cells.push(makeMarkdownCell([
      `### 📊 Output Analysis\n`,
      `\n`,
      `${task.outputAnalysis}\n`,
      `\n`,
      `---`,
    ]));
  });

  // Conclusion
  if (labData.conclusion) {
    cells.push(makeMarkdownCell([
      `## 📋 Conclusion\n`,
      `\n`,
      `${labData.conclusion}`,
    ]));
  }

  const notebook = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: 'Python 3',
        language: 'python',
        name: 'python3',
      },
      language_info: {
        name: 'python',
        version: '3.11.0',
      },
    },
    cells,
  };

  return notebook;
}

/**
 * Trigger browser download of the .ipynb file
 */
export function downloadNotebook(labData, executionResults = []) {
  const notebook = generateNotebook(labData, executionResults);
  const json = JSON.stringify(notebook, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const url = URL.createObjectURL(blob);

  const fileName = (labData.reportTitle || 'lab_report')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '')
    + '.ipynb';

  const a = document.createElement('a');
  document.body.appendChild(a);
  a.style.display = 'none';
  a.href = url;
  a.download = fileName;
  a.click();
  
  // Give the browser time to initiate the download before cleaning up
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 100);
}
