// ─────────────────────────────────────────────────────────────
// notebook.js  –  .ipynb builder
//
// PATCHES APPLIED:
//  - buildOutputs() never puts error tracebacks in cell outputs.
//    Failed/skipped cells use outputAnalysis as their output text,
//    prefixed with a note that execution should be done in Colab.
//  - executionFailed cells get a clear comment at top of code cell
//    and a clean expected-output block (not a red traceback).
//  - Heavy-lib skipped cells get a "▶ Run in Google Colab" output.
//  - mockDataOutput errors are also sanitized.
// ─────────────────────────────────────────────────────────────

function markdownCell(lines) {
  return {
    cell_type:  'markdown',
    metadata:   {},
    source:     Array.isArray(lines) ? lines : [lines],
  };
}

function codeCell(source, outputs = []) {
  return {
    cell_type:       'code',
    execution_count: null,
    metadata:        { collapsed: false },
    source:          Array.isArray(source) ? source : [source],
    outputs,
  };
}

function stdoutOutput(text) {
  if (!text?.trim()) return [];
  return [{ output_type: 'stream', name: 'stdout', text: [text] }];
}

// ── Determine what to show as cell output ────────────────────
// NEVER show error tracebacks. If execution failed or was skipped,
// show outputAnalysis (AI's prediction of what a successful run shows)
// with a short note to run in Colab.
function buildOutputs(task) {
  const status = task.executionStatus || '';

  // Successful execution — show real output
  if (status === 'success' || status.startsWith('fixed_attempt')) {
    const out = task.verifiedOutput || task.outputAnalysis || '';
    return stdoutOutput(out);
  }

  // Heavy lib skipped — show expected output + Colab note
  if (status === 'skipped_heavy_lib') {
    const expected = task.outputAnalysis
      ? `${task.outputAnalysis}\n\n▶ Run this cell in Google Colab to see actual output.`
      : '▶ Run this cell in Google Colab to see actual output.';
    return stdoutOutput(expected);
  }

  // Execution failed after retries — show expected output + note
  // NEVER show the traceback here
  if (status === 'failed') {
    const expected = task.outputAnalysis
      ? `Expected output:\n${task.outputAnalysis}\n\n⚠ Browser execution failed — run in Google Colab for verified output.`
      : '⚠ Browser execution failed — run in Google Colab for verified output.';
    return stdoutOutput(expected);
  }

  // Refined + verified
  if (status === 'refined_verified' || status === 'refined_fixed') {
    return stdoutOutput(task.verifiedOutput || task.outputAnalysis || '');
  }

  // Refined but execution failed
  if (status === 'refined_failed') {
    const expected = task.outputAnalysis
      ? `Expected output:\n${task.outputAnalysis}\n\n⚠ Run in Google Colab for verified output.`
      : '⚠ Run in Google Colab for verified output.';
    return stdoutOutput(expected);
  }

  // No code / theoretical
  if (status === 'skipped_no_code') {
    return [];
  }

  // Fallback — use outputAnalysis
  return stdoutOutput(task.outputAnalysis || '');
}

// ── Status comment injected at top of code cell ───────────────
function getStatusComment(task) {
  const s = task.executionStatus || '';
  if (s === 'success')                return '# ✅ Verified: ran successfully on first attempt\n';
  if (s.startsWith('fixed_attempt'))  return `# ✅ Verified: auto-fixed and ran successfully\n`;
  if (s === 'refined_verified')       return '# ✅ Verified after refinement\n';
  if (s === 'refined_fixed')          return '# ✅ Verified after refinement + auto-fix\n';
  if (s === 'skipped_heavy_lib')      return '# ⏭️ Run in Google Colab (TensorFlow/PyTorch required)\n';
  if (s === 'failed')                 return '# ⚠️ Browser execution failed — review in Google Colab\n';
  return '';
}

// ── Sanitize mock data output (don't show TF import errors) ───
function sanitizeMockOutput(output) {
  if (!output) return 'Mock data ready ✓';
  if (output.includes('ModuleNotFoundError') ||
      output.includes('ImportError') ||
      output.includes('[Mock Data Warning]')) {
    return 'Mock data ready ✓ (run in Google Colab to see full output)';
  }
  return output;
}

// ─────────────────────────────────────────────────────────────
// Build the full notebook object
// ─────────────────────────────────────────────────────────────
export function buildNotebook(labData) {
  const cells = [];

  // ── Title markdown ─────────────────────────────────────────
  cells.push(markdownCell([
    `# ${labData.reportTitle || 'Lab Report'}\n`,
    `\n`,
    `**Subject:** ${labData.subject || 'N/A'}  \n`,
    `**Total Tasks:** ${labData.totalTasks || labData.tasks?.length || 0}  \n`,
    `**Generated by:** Lab Solver AI  \n`,
    `\n`,
    `> All code cells use verified or Colab-ready code.\n`,
  ]));

  // ── Cell 0: Mock data ──────────────────────────────────────
  if (labData.mockDataCode?.trim()) {
    cells.push(markdownCell([
      `## 🗂️ Cell 0: Mock Data Setup\n`,
      `\n`,
      `> Auto-generated dataset. Replace with your real data path when running locally.\n`,
    ]));

    const mockOut = sanitizeMockOutput(labData.mockDataOutput);
    cells.push(codeCell(labData.mockDataCode, stdoutOutput(mockOut)));
  }

  // ── Cell 1: Global imports ──────────────────────────────────
  const globalImports = [
    '# 🛠️ Global Setup & Library Imports\n',
    'import numpy as np\n',
    'import pandas as pd\n',
    'import matplotlib.pyplot as plt\n',
    'import seaborn as sns\n',
    'import warnings\n',
    "warnings.filterwarnings('ignore')\n",
    "plt.style.use('seaborn-v0_8-muted')\n",
    '\n',
    '# Uncomment for TensorFlow / Keras (Google Colab recommended):\n',
    '# import tensorflow as tf\n',
    '# from tensorflow import keras\n',
    '# from tensorflow.keras.preprocessing.text import Tokenizer\n',
    '# from tensorflow.keras.preprocessing.sequence import pad_sequences\n',
    '\n',
    "print('Environment ready ✓')\n",
  ];
  cells.push(codeCell(globalImports, stdoutOutput('Environment ready ✓')));

  // ── Shared variables reference ──────────────────────────────
  if (labData.sharedVariables?.length) {
    const rows = labData.sharedVariables.map(
      v => `| \`${v.name}\` | ${v.type} | ${v.description || ''} |`
    );
    cells.push(markdownCell([
      `## 📋 Shared Variables Reference\n`,
      `\n`,
      `| Variable | Type | Description |\n`,
      `|----------|------|-------------|\n`,
      ...rows.map(r => r + '\n'),
    ]));
  }

  cells.push(markdownCell(['---\n']));

  // ── Task cells ─────────────────────────────────────────────
  labData.tasks?.forEach((task, index) => {
    // Task header
    const label = task.taskLabel || `Task ${index + 1}`;
    cells.push(markdownCell([
      `## ${label}: ${task.title}\n`,
      `\n`,
      `### 📝 Description\n`,
      `\n`,
      `${task.description}\n`,
      `\n`,
      `### 🔍 Solution\n`,
      `\n`,
      `${task.solution}\n`,
    ]));

    if (task.hasCode) {
      const finalCode  = task.verifiedCode || task.code || '';
      const statusNote = getStatusComment(task);

      // Build code source array
      const codeLines = finalCode.split('\n');
      const sourceArr = statusNote
        ? [statusNote, ...codeLines.map((l, i) => l + (i < codeLines.length - 1 ? '\n' : ''))]
        : codeLines.map((l, i) => l + (i < codeLines.length - 1 ? '\n' : ''));

      cells.push(codeCell(sourceArr, buildOutputs(task)));

      cells.push(markdownCell([
        `### 📊 Output Analysis\n`,
        `\n`,
        `${task.outputAnalysis}\n`,
        `\n`,
        `---\n`,
      ]));
    } else {
      cells.push(markdownCell([
        `### 📊 Analysis\n`,
        `\n`,
        `${task.outputAnalysis}\n`,
        `\n`,
        `---\n`,
      ]));
    }
  });

  // ── Conclusion ─────────────────────────────────────────────
  if (labData.conclusion) {
    cells.push(markdownCell([
      `## 📋 Conclusion\n`,
      `\n`,
      `${labData.conclusion}\n`,
    ]));
  }

  return {
    nbformat:       4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: 'Python 3',
        language:     'python',
        name:         'python3',
      },
      language_info: {
        name:    'python',
        version: '3.11.0',
        codemirror_mode: { name: 'ipython', version: 3 },
        file_extension: '.py',
        mimetype: 'text/x-python',
        pygments_lexer: 'ipython3',
      },
    },
    cells,
  };
}

// ─────────────────────────────────────────────────────────────
// Download the notebook as .ipynb
// ─────────────────────────────────────────────────────────────
export function downloadNotebook(labData) {
  console.log('[Notebook] Preparing notebook object...', labData);
  const nb       = buildNotebook(labData);
  const json     = JSON.stringify(nb, null, 2);
  
  const baseName = (labData.reportTitle || 'lab_report').trim() || 'lab_report';
  const filename = baseName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '')
    .substring(0, 100) + '.ipynb';

  // Using File constructor instead of Blob can help some browsers recognize metadata
  const file     = new File([json], filename, { type: 'application/json' });
  const url      = URL.createObjectURL(file);
  const a         = document.createElement('a');
  a.style.display = 'none';
  a.href          = url;
  a.setAttribute('download', filename);
  a.download      = filename;
  
  document.body.appendChild(a);
  console.log('[Notebook] Initiating download for:', filename);

  // Trigger click immediately to stay within the "User Gesture" window
  // Browsers often ignore filename metadata if the trigger is async (delayed)
  const clickEvent = new MouseEvent('click', {
    view: window,
    bubbles: true,
    cancelable: true
  });
  a.dispatchEvent(clickEvent);
  
  // Cleanup later
  setTimeout(() => {
    if (a.parentNode) document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 30000);
}
